spring.application.name=codetickets
spring.datasource.url=jdbc:postgresql://localhost/codetickets_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASWORD}
spring.jpa.hibernate.ddl-auto=update
spring.batch.jdbc.initialize-schema=always
